# Top Ranking Group By Request
ranking_count = 20

# Top Slow Requests
slow_count = 37

# Show Standard Deviation column
show_stddev = true

# Show HTTP Status Code columns
show_status_code = true

# Show HTTP Response Bytes columns
show_bytes = true

# Percentiles
percentiles = [ 50.0, 90.0, 95.0, 99.0 ]

# for Nginx($request_time)
scale = 0
effective_digit = 3

# for Apache(%D) and Varnishncsa(%D)
#scale = -6
#effective_digit = 6

# for Rack(Rack::CommonLogger)
#scale = 0
#effective_digit = 4


# combined + duration
# Nginx example: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time'
# Apache example: "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %D"
# H2O example: "%h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\" %{duration}x"
# Varnishncsa example: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-agent}i" %D'
# [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"\n
# [2021-08-09T01:21:38.047Z] "GET / HTTP/2" 200 - 0 389 22 21 "150.249.153.34" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "c3cf7ead-5cb9-4e5b-9a10-601f3b1b5bf8" "app.t.isucon.dev" "127.0.0.1:9292"
log_format = '^([^ ]+) ([^ ]+) ([^ ]+) \[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) (\d+|-) "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" ([0-9.]+)$'

request_index = 2
status_index = 3
bytes_index = 
duration_index = 10

# Rack example: use Rack::CommonLogger, Logger.new("/tmp/app.log")
#log_format = '^([^ ]+) ([^ ]+) ([^ ]+) \[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) (\d+|-) ([0-9.]+)$'
#request_index = 5
#status_index = 6
#bytes_index = 7
#duration_index = 8

# You can aggregate requests by regular expression
# For overview of regexp syntax: https://golang.org/pkg/regexp/syntax/
[[bundle]]
regexp = '^(GET|HEAD) /memo/[0-9]+\b'
name = "get memo"

[[bundle]]
regexp = '^(GET|HEAD) /stylesheets/'
name = "stylesheets"

[[bundle]]
regexp = '^(GET|HEAD) /images/'
name = "images"

# You can replace the part of urls which matched to your regular expressions.
# For overview of regexp syntax: https://golang.org/pkg/regexp/syntax/
#[[replace]]
#regexp = '/[0-9]+/'
#replace = '/<num>/'
#
#[[replace]]
#regexp = '/[0-9]+\s'
#replace = '/<num> '
#
#[[replace]]
#regexp = '=[0-9]+&'
#replace = '=<num>&'
#
#[[replace]]
#regexp = '=[0-9]+\s'
#replace = '=<num> '
